"scope: app":
  - changed-files:
      - any-glob-to-any-file: "packages/nastech-app/sources/**"

"scope: agent":
  - changed-files:
      - any-glob-to-any-file: "nastech-agent/**"

"scope: ci":
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
      - any-glob-to-any-file: ".github/dependabot.yml"

"scope: termux":
  - changed-files:
      - any-glob-to-any-file: "packages/nastech-app/plugins/**"
      - any-glob-to-any-file: "packages/nastech-app/eas-build-pre-install.sh"

"scope: desktop":
  - changed-files:
      - any-glob-to-any-file: "packages/nastech-app/src-tauri/**"

"scope: config":
  - changed-files:
      - any-glob-to-any-file: "packages/nastech-app/app.config.js"
      - any-glob-to-any-file: "packages/nastech-app/eas.json"

"scope: ios":
  - changed-files:
      - any-glob-to-any-file: "packages/nastech-app/sources/(app)/server.tsx"

"type: deps":
  - changed-files:
      - any-glob-to-any-file: "package.json"
      - any-glob-to-any-file: "packages/nastech-app/package.json"
      - any-glob-to-any-file: "renovate.json"
      - any-glob-to-any-file: "nastech-agent/requirements*.txt"

"type: docs":
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
      - any-glob-to-any-file: "CHANGELOG*"

"type: release":
  - changed-files:
      - any-glob-to-any-file: "CHANGELOG*"
      - any-glob-to-any-file: ".release-please-manifest.json"
