# Pulled from: https://github.com/renovatebot/renovate/blob/main/.github/workflows/label-actions.yml
name: Label Actions

on:
  issues:
    types: [labeled]
  discussion:
    types: [labeled]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  issues: write
  discussions: write
  pull-requests: write

jobs:
  reaction:
    name: React to label
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v5.0.3
        with:
          github-token: ${{ github.token }}
          config-path: .github/label-actions.yml
